[package]
name = "firebird702/profileservice"
version = "1.0.1"
license = "Apache License 2.0"
authors = ["loleris"]
description = "Forked ProfileService"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
